[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"  # Asegúrate de que la carpeta de funciones esté configurada correctamente si usas funciones Netlify

[build.environment]
  NODE_VERSION = "14"  # Puedes ajustar esto según la versión de Node.js que estés utilizando en tu proyecto

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Si estás usando funciones Netlify con Next.js, por ejemplo, asegúrate de agregar el plugin correspondiente

[context.production.environment]
  NODE_ENV = "production"
